// src/councils.js — UK local authorities/councils
// URLs point to Google search "<council name> jobs" — update to direct careers URLs when available
// Data current as of 2026 UK local government structure

const raw = [
  // ═══ LONDON BOROUGHS (33) ═══
  { name: "Barking and Dagenham",      region: "London", type: "London Borough" },
  { name: "Barnet",                    region: "London", type: "London Borough" },
  { name: "Bexley",                    region: "London", type: "London Borough" },
  { name: "Brent",                     region: "London", type: "London Borough" },
  { name: "Bromley",                   region: "London", type: "London Borough" },
  { name: "Camden",                    region: "London", type: "London Borough" },
  { name: "City of London",            region: "London", type: "City" },
  { name: "Croydon",                   region: "London", type: "London Borough" },
  { name: "Ealing",                    region: "London", type: "London Borough" },
  { name: "Enfield",                   region: "London", type: "London Borough" },
  { name: "Greenwich",                 region: "London", type: "London Borough" },
  { name: "Hackney",                   region: "London", type: "London Borough" },
  { name: "Hammersmith and Fulham",    region: "London", type: "London Borough" },
  { name: "Haringey",                  region: "London", type: "London Borough" },
  { name: "Harrow",                    region: "London", type: "London Borough" },
  { name: "Havering",                  region: "London", type: "London Borough" },
  { name: "Hillingdon",                region: "London", type: "London Borough" },
  { name: "Hounslow",                  region: "London", type: "London Borough" },
  { name: "Islington",                 region: "London", type: "London Borough" },
  { name: "Kensington and Chelsea",    region: "London", type: "Royal Borough" },
  { name: "Kingston upon Thames",      region: "London", type: "Royal Borough" },
  { name: "Lambeth",                   region: "London", type: "London Borough" },
  { name: "Lewisham",                  region: "London", type: "London Borough" },
  { name: "Merton",                    region: "London", type: "London Borough" },
  { name: "Newham",                    region: "London", type: "London Borough" },
  { name: "Redbridge",                 region: "London", type: "London Borough" },
  { name: "Richmond upon Thames",      region: "London", type: "London Borough" },
  { name: "Southwark",                 region: "London", type: "London Borough" },
  { name: "Sutton",                    region: "London", type: "London Borough" },
  { name: "Tower Hamlets",             region: "London", type: "London Borough" },
  { name: "Waltham Forest",            region: "London", type: "London Borough" },
  { name: "Wandsworth",                region: "London", type: "London Borough" },
  { name: "Westminster",               region: "London", type: "City" },

  // ═══ METROPOLITAN BOROUGHS (36) ═══
  { name: "Barnsley",                  region: "Yorkshire and the Humber", type: "Metropolitan Borough" },
  { name: "Birmingham",                region: "West Midlands", type: "Metropolitan Borough" },
  { name: "Bolton",                    region: "North West", type: "Metropolitan Borough" },
  { name: "Bradford",                  region: "Yorkshire and the Humber", type: "Metropolitan Borough" },
  { name: "Bury",                      region: "North West", type: "Metropolitan Borough" },
  { name: "Calderdale",                region: "Yorkshire and the Humber", type: "Metropolitan Borough" },
  { name: "Coventry",                  region: "West Midlands", type: "Metropolitan Borough" },
  { name: "Doncaster",                 region: "Yorkshire and the Humber", type: "Metropolitan Borough" },
  { name: "Dudley",                    region: "West Midlands", type: "Metropolitan Borough" },
  { name: "Gateshead",                 region: "North East", type: "Metropolitan Borough" },
  { name: "Kirklees",                  region: "Yorkshire and the Humber", type: "Metropolitan Borough" },
  { name: "Knowsley",                  region: "North West", type: "Metropolitan Borough" },
  { name: "Leeds",                     region: "Yorkshire and the Humber", type: "Metropolitan Borough" },
  { name: "Liverpool",                 region: "North West", type: "Metropolitan Borough" },
  { name: "Manchester",                region: "North West", type: "Metropolitan Borough" },
  { name: "Newcastle upon Tyne",       region: "North East", type: "Metropolitan Borough" },
  { name: "North Tyneside",            region: "North East", type: "Metropolitan Borough" },
  { name: "Oldham",                    region: "North West", type: "Metropolitan Borough" },
  { name: "Rochdale",                  region: "North West", type: "Metropolitan Borough" },
  { name: "Rotherham",                 region: "Yorkshire and the Humber", type: "Metropolitan Borough" },
  { name: "Salford",                   region: "North West", type: "Metropolitan Borough" },
  { name: "Sandwell",                  region: "West Midlands", type: "Metropolitan Borough" },
  { name: "Sefton",                    region: "North West", type: "Metropolitan Borough" },
  { name: "Sheffield",                 region: "Yorkshire and the Humber", type: "Metropolitan Borough" },
  { name: "Solihull",                  region: "West Midlands", type: "Metropolitan Borough" },
  { name: "South Tyneside",            region: "North East", type: "Metropolitan Borough" },
  { name: "St Helens",                 region: "North West", type: "Metropolitan Borough" },
  { name: "Stockport",                 region: "North West", type: "Metropolitan Borough" },
  { name: "Sunderland",                region: "North East", type: "Metropolitan Borough" },
  { name: "Tameside",                  region: "North West", type: "Metropolitan Borough" },
  { name: "Trafford",                  region: "North West", type: "Metropolitan Borough" },
  { name: "Wakefield",                 region: "Yorkshire and the Humber", type: "Metropolitan Borough" },
  { name: "Walsall",                   region: "West Midlands", type: "Metropolitan Borough" },
  { name: "Wigan",                     region: "North West", type: "Metropolitan Borough" },
  { name: "Wirral",                    region: "North West", type: "Metropolitan Borough" },
  { name: "Wolverhampton",             region: "West Midlands", type: "Metropolitan Borough" },

  // ═══ UNITARY AUTHORITIES ═══
  { name: "Bath and North East Somerset", region: "South West", type: "Unitary" },
  { name: "Bedford",                   region: "East of England", type: "Unitary" },
  { name: "Blackburn with Darwen",     region: "North West", type: "Unitary" },
  { name: "Blackpool",                 region: "North West", type: "Unitary" },
  { name: "Bournemouth, Christchurch and Poole", region: "South West", type: "Unitary" },
  { name: "Bracknell Forest",          region: "South East", type: "Unitary" },
  { name: "Brighton and Hove",         region: "South East", type: "Unitary" },
  { name: "Bristol",                   region: "South West", type: "Unitary" },
  { name: "Buckinghamshire",           region: "South East", type: "Unitary" },
  { name: "Central Bedfordshire",      region: "East of England", type: "Unitary" },
  { name: "Cheshire East",             region: "North West", type: "Unitary" },
  { name: "Cheshire West and Chester", region: "North West", type: "Unitary" },
  { name: "Cornwall",                  region: "South West", type: "Unitary" },
  { name: "Cumberland",                region: "North West", type: "Unitary" },
  { name: "Darlington",                region: "North East", type: "Unitary" },
  { name: "Derby",                     region: "East Midlands", type: "Unitary" },
  { name: "Dorset",                    region: "South West", type: "Unitary" },
  { name: "Durham",                    region: "North East", type: "Unitary" },
  { name: "East Riding of Yorkshire",  region: "Yorkshire and the Humber", type: "Unitary" },
  { name: "Halton",                    region: "North West", type: "Unitary" },
  { name: "Hartlepool",                region: "North East", type: "Unitary" },
  { name: "Herefordshire",             region: "West Midlands", type: "Unitary" },
  { name: "Hull",                      region: "Yorkshire and the Humber", type: "Unitary" },
  { name: "Isle of Wight",             region: "South East", type: "Unitary" },
  { name: "Leicester",                 region: "East Midlands", type: "Unitary" },
  { name: "Luton",                     region: "East of England", type: "Unitary" },
  { name: "Medway",                    region: "South East", type: "Unitary" },
  { name: "Middlesbrough",             region: "North East", type: "Unitary" },
  { name: "Milton Keynes",             region: "South East", type: "Unitary" },
  { name: "North East Lincolnshire",   region: "Yorkshire and the Humber", type: "Unitary" },
  { name: "North Lincolnshire",        region: "Yorkshire and the Humber", type: "Unitary" },
  { name: "North Northamptonshire",    region: "East Midlands", type: "Unitary" },
  { name: "North Somerset",            region: "South West", type: "Unitary" },
  { name: "North Yorkshire",           region: "Yorkshire and the Humber", type: "Unitary" },
  { name: "Northumberland",            region: "North East", type: "Unitary" },
  { name: "Nottingham",                region: "East Midlands", type: "Unitary" },
  { name: "Peterborough",              region: "East of England", type: "Unitary" },
  { name: "Plymouth",                  region: "South West", type: "Unitary" },
  { name: "Portsmouth",                region: "South East", type: "Unitary" },
  { name: "Reading",                   region: "South East", type: "Unitary" },
  { name: "Redcar and Cleveland",      region: "North East", type: "Unitary" },
  { name: "Rutland",                   region: "East Midlands", type: "Unitary" },
  { name: "Shropshire",                region: "West Midlands", type: "Unitary" },
  { name: "Slough",                    region: "South East", type: "Unitary" },
  { name: "Somerset",                  region: "South West", type: "Unitary" },
  { name: "South Gloucestershire",     region: "South West", type: "Unitary" },
  { name: "Southampton",               region: "South East", type: "Unitary" },
  { name: "Southend-on-Sea",           region: "East of England", type: "Unitary" },
  { name: "Stockton-on-Tees",          region: "North East", type: "Unitary" },
  { name: "Stoke-on-Trent",            region: "West Midlands", type: "Unitary" },
  { name: "Swindon",                   region: "South West", type: "Unitary" },
  { name: "Telford and Wrekin",        region: "West Midlands", type: "Unitary" },
  { name: "Thurrock",                  region: "East of England", type: "Unitary" },
  { name: "Torbay",                    region: "South West", type: "Unitary" },
  { name: "Warrington",                region: "North West", type: "Unitary" },
  { name: "West Berkshire",            region: "South East", type: "Unitary" },
  { name: "West Northamptonshire",     region: "East Midlands", type: "Unitary" },
  { name: "Westmorland and Furness",   region: "North West", type: "Unitary" },
  { name: "Wiltshire",                 region: "South West", type: "Unitary" },
  { name: "Windsor and Maidenhead",    region: "South East", type: "Royal Borough" },
  { name: "Wokingham",                 region: "South East", type: "Unitary" },
  { name: "York",                      region: "Yorkshire and the Humber", type: "Unitary" },

  // ═══ COUNTY COUNCILS ═══
  { name: "Cambridgeshire County Council",    region: "East of England", type: "County" },
  { name: "Derbyshire County Council",        region: "East Midlands", type: "County" },
  { name: "Devon County Council",             region: "South West", type: "County" },
  { name: "East Sussex County Council",       region: "South East", type: "County" },
  { name: "Essex County Council",             region: "East of England", type: "County" },
  { name: "Gloucestershire County Council",   region: "South West", type: "County" },
  { name: "Hampshire County Council",         region: "South East", type: "County" },
  { name: "Hertfordshire County Council",     region: "East of England", type: "County" },
  { name: "Kent County Council",              region: "South East", type: "County" },
  { name: "Lancashire County Council",        region: "North West", type: "County" },
  { name: "Leicestershire County Council",    region: "East Midlands", type: "County" },
  { name: "Lincolnshire County Council",      region: "East Midlands", type: "County" },
  { name: "Norfolk County Council",           region: "East of England", type: "County" },
  { name: "Nottinghamshire County Council",   region: "East Midlands", type: "County" },
  { name: "Oxfordshire County Council",       region: "South East", type: "County" },
  { name: "Staffordshire County Council",     region: "West Midlands", type: "County" },
  { name: "Suffolk County Council",           region: "East of England", type: "County" },
  { name: "Surrey County Council",            region: "South East", type: "County" },
  { name: "Warwickshire County Council",      region: "West Midlands", type: "County" },
  { name: "West Sussex County Council",       region: "South East", type: "County" },
  { name: "Worcestershire County Council",    region: "West Midlands", type: "County" },

  // ═══ DISTRICT/BOROUGH COUNCILS (selected — top ~180) ═══
  // East Midlands Districts
  { name: "Amber Valley",              region: "East Midlands", type: "Borough" },
  { name: "Ashfield",                  region: "East Midlands", type: "District" },
  { name: "Bassetlaw",                 region: "East Midlands", type: "District" },
  { name: "Blaby",                     region: "East Midlands", type: "District" },
  { name: "Bolsover",                  region: "East Midlands", type: "District" },
  { name: "Boston",                    region: "East Midlands", type: "Borough" },
  { name: "Broxtowe",                  region: "East Midlands", type: "Borough" },
  { name: "Charnwood",                 region: "East Midlands", type: "Borough" },
  { name: "Chesterfield",              region: "East Midlands", type: "Borough" },
  { name: "Derbyshire Dales",          region: "East Midlands", type: "District" },
  { name: "East Lindsey",              region: "East Midlands", type: "District" },
  { name: "Erewash",                   region: "East Midlands", type: "Borough" },
  { name: "Gedling",                   region: "East Midlands", type: "Borough" },
  { name: "Harborough",                region: "East Midlands", type: "District" },
  { name: "High Peak",                 region: "East Midlands", type: "Borough" },
  { name: "Hinckley and Bosworth",     region: "East Midlands", type: "Borough" },
  { name: "Lincoln",                   region: "East Midlands", type: "City" },
  { name: "Mansfield",                 region: "East Midlands", type: "District" },
  { name: "Melton",                    region: "East Midlands", type: "Borough" },
  { name: "Newark and Sherwood",       region: "East Midlands", type: "District" },
  { name: "North East Derbyshire",     region: "East Midlands", type: "District" },
  { name: "North Kesteven",            region: "East Midlands", type: "District" },
  { name: "North West Leicestershire", region: "East Midlands", type: "District" },
  { name: "Oadby and Wigston",         region: "East Midlands", type: "Borough" },
  { name: "Rushcliffe",                region: "East Midlands", type: "Borough" },
  { name: "South Derbyshire",          region: "East Midlands", type: "District" },
  { name: "South Holland",             region: "East Midlands", type: "District" },
  { name: "South Kesteven",            region: "East Midlands", type: "District" },
  { name: "West Lindsey",              region: "East Midlands", type: "District" },

  // East of England Districts
  { name: "Babergh",                   region: "East of England", type: "District" },
  { name: "Basildon",                  region: "East of England", type: "Borough" },
  { name: "Braintree",                 region: "East of England", type: "District" },
  { name: "Breckland",                 region: "East of England", type: "District" },
  { name: "Brentwood",                 region: "East of England", type: "Borough" },
  { name: "Broadland",                 region: "East of England", type: "District" },
  { name: "Broxbourne",                region: "East of England", type: "Borough" },
  { name: "Cambridge",                 region: "East of England", type: "City" },
  { name: "Castle Point",              region: "East of England", type: "Borough" },
  { name: "Chelmsford",                region: "East of England", type: "City" },
  { name: "Colchester",                region: "East of England", type: "City" },
  { name: "Dacorum",                   region: "East of England", type: "Borough" },
  { name: "East Cambridgeshire",       region: "East of England", type: "District" },
  { name: "East Hertfordshire",        region: "East of England", type: "District" },
  { name: "East Suffolk",              region: "East of England", type: "District" },
  { name: "Epping Forest",             region: "East of England", type: "District" },
  { name: "Fenland",                   region: "East of England", type: "District" },
  { name: "Great Yarmouth",            region: "East of England", type: "Borough" },
  { name: "Harlow",                    region: "East of England", type: "District" },
  { name: "Hertsmere",                 region: "East of England", type: "Borough" },
  { name: "Huntingdonshire",           region: "East of England", type: "District" },
  { name: "Ipswich",                   region: "East of England", type: "Borough" },
  { name: "King's Lynn and West Norfolk", region: "East of England", type: "Borough" },
  { name: "Maldon",                    region: "East of England", type: "District" },
  { name: "Mid Suffolk",               region: "East of England", type: "District" },
  { name: "North Hertfordshire",       region: "East of England", type: "District" },
  { name: "North Norfolk",             region: "East of England", type: "District" },
  { name: "Norwich",                   region: "East of England", type: "City" },
  { name: "Rochford",                  region: "East of England", type: "District" },
  { name: "South Cambridgeshire",      region: "East of England", type: "District" },
  { name: "South Norfolk",             region: "East of England", type: "District" },
  { name: "St Albans",                 region: "East of England", type: "City" },
  { name: "Stevenage",                 region: "East of England", type: "Borough" },
  { name: "Tendring",                  region: "East of England", type: "District" },
  { name: "Three Rivers",              region: "East of England", type: "District" },
  { name: "Uttlesford",                region: "East of England", type: "District" },
  { name: "Watford",                   region: "East of England", type: "Borough" },
  { name: "Welwyn Hatfield",           region: "East of England", type: "Borough" },
  { name: "West Suffolk",              region: "East of England", type: "District" },

  // South East Districts
  { name: "Adur",                      region: "South East", type: "District" },
  { name: "Arun",                      region: "South East", type: "District" },
  { name: "Ashford",                   region: "South East", type: "Borough" },
  { name: "Basingstoke and Deane",     region: "South East", type: "Borough" },
  { name: "Canterbury",                region: "South East", type: "City" },
  { name: "Cherwell",                  region: "South East", type: "District" },
  { name: "Chichester",                region: "South East", type: "District" },
  { name: "Crawley",                   region: "South East", type: "Borough" },
  { name: "Dartford",                  region: "South East", type: "Borough" },
  { name: "Dover",                     region: "South East", type: "District" },
  { name: "East Hampshire",            region: "South East", type: "District" },
  { name: "Eastbourne",                region: "South East", type: "Borough" },
  { name: "Eastleigh",                 region: "South East", type: "Borough" },
  { name: "Elmbridge",                 region: "South East", type: "Borough" },
  { name: "Epsom and Ewell",           region: "South East", type: "Borough" },
  { name: "Fareham",                   region: "South East", type: "Borough" },
  { name: "Folkestone and Hythe",      region: "South East", type: "District" },
  { name: "Gosport",                   region: "South East", type: "Borough" },
  { name: "Gravesham",                 region: "South East", type: "Borough" },
  { name: "Guildford",                 region: "South East", type: "Borough" },
  { name: "Hart",                      region: "South East", type: "District" },
  { name: "Hastings",                  region: "South East", type: "Borough" },
  { name: "Havant",                    region: "South East", type: "Borough" },
  { name: "Horsham",                   region: "South East", type: "District" },
  { name: "Lewes",                     region: "South East", type: "District" },
  { name: "Maidstone",                 region: "South East", type: "Borough" },
  { name: "Mid Sussex",                region: "South East", type: "District" },
  { name: "Mole Valley",               region: "South East", type: "District" },
  { name: "New Forest",                region: "South East", type: "District" },
  { name: "Oxford",                    region: "South East", type: "City" },
  { name: "Reigate and Banstead",      region: "South East", type: "Borough" },
  { name: "Rother",                    region: "South East", type: "District" },
  { name: "Runnymede",                 region: "South East", type: "Borough" },
  { name: "Rushmoor",                  region: "South East", type: "Borough" },
  { name: "Sevenoaks",                 region: "South East", type: "District" },
  { name: "South Oxfordshire",         region: "South East", type: "District" },
  { name: "Spelthorne",                region: "South East", type: "Borough" },
  { name: "Surrey Heath",              region: "South East", type: "Borough" },
  { name: "Swale",                     region: "South East", type: "Borough" },
  { name: "Tandridge",                 region: "South East", type: "District" },
  { name: "Test Valley",               region: "South East", type: "Borough" },
  { name: "Thanet",                    region: "South East", type: "District" },
  { name: "Tonbridge and Malling",     region: "South East", type: "Borough" },
  { name: "Tunbridge Wells",           region: "South East", type: "Borough" },
  { name: "Vale of White Horse",       region: "South East", type: "District" },
  { name: "Waverley",                  region: "South East", type: "Borough" },
  { name: "Wealden",                   region: "South East", type: "District" },
  { name: "West Oxfordshire",          region: "South East", type: "District" },
  { name: "Winchester",                region: "South East", type: "City" },
  { name: "Woking",                    region: "South East", type: "Borough" },
  { name: "Worthing",                  region: "South East", type: "Borough" },

  // South West Districts
  { name: "Cotswold",                  region: "South West", type: "District" },
  { name: "East Devon",                region: "South West", type: "District" },
  { name: "Exeter",                    region: "South West", type: "City" },
  { name: "Forest of Dean",            region: "South West", type: "District" },
  { name: "Gloucester",                region: "South West", type: "City" },
  { name: "Mendip",                    region: "South West", type: "District" },
  { name: "Mid Devon",                 region: "South West", type: "District" },
  { name: "North Devon",               region: "South West", type: "District" },
  { name: "Sedgemoor",                 region: "South West", type: "District" },
  { name: "Somerset West and Taunton", region: "South West", type: "District" },
  { name: "South Hams",                region: "South West", type: "District" },
  { name: "South Somerset",            region: "South West", type: "District" },
  { name: "Stroud",                    region: "South West", type: "District" },
  { name: "Teignbridge",               region: "South West", type: "District" },
  { name: "Tewkesbury",                region: "South West", type: "Borough" },
  { name: "Torridge",                  region: "South West", type: "District" },
  { name: "West Devon",                region: "South West", type: "Borough" },

  // West Midlands Districts
  { name: "Bromsgrove",                region: "West Midlands", type: "District" },
  { name: "Cannock Chase",             region: "West Midlands", type: "District" },
  { name: "East Staffordshire",        region: "West Midlands", type: "Borough" },
  { name: "Lichfield",                 region: "West Midlands", type: "District" },
  { name: "Malvern Hills",             region: "West Midlands", type: "District" },
  { name: "Newcastle-under-Lyme",      region: "West Midlands", type: "Borough" },
  { name: "North Warwickshire",        region: "West Midlands", type: "Borough" },
  { name: "Nuneaton and Bedworth",     region: "West Midlands", type: "Borough" },
  { name: "Redditch",                  region: "West Midlands", type: "Borough" },
  { name: "Rugby",                     region: "West Midlands", type: "Borough" },
  { name: "Stafford",                  region: "West Midlands", type: "Borough" },
  { name: "Staffordshire Moorlands",   region: "West Midlands", type: "District" },
  { name: "Stratford-on-Avon",         region: "West Midlands", type: "District" },
  { name: "Tamworth",                  region: "West Midlands", type: "Borough" },
  { name: "Warwick",                   region: "West Midlands", type: "District" },
  { name: "Worcester",                 region: "West Midlands", type: "City" },
  { name: "Wychavon",                  region: "West Midlands", type: "District" },
  { name: "Wyre Forest",               region: "West Midlands", type: "District" },

  // North West Districts
  { name: "Burnley",                   region: "North West", type: "Borough" },
  { name: "Chorley",                   region: "North West", type: "Borough" },
  { name: "Fylde",                     region: "North West", type: "Borough" },
  { name: "Hyndburn",                  region: "North West", type: "Borough" },
  { name: "Lancaster",                 region: "North West", type: "City" },
  { name: "Pendle",                    region: "North West", type: "Borough" },
  { name: "Preston",                   region: "North West", type: "City" },
  { name: "Ribble Valley",             region: "North West", type: "Borough" },
  { name: "Rossendale",                region: "North West", type: "Borough" },
  { name: "South Ribble",              region: "North West", type: "Borough" },
  { name: "West Lancashire",           region: "North West", type: "Borough" },
  { name: "Wyre",                      region: "North West", type: "Borough" },

  // Yorkshire Districts
  { name: "Craven",                    region: "Yorkshire and the Humber", type: "District" },
  { name: "Hambleton",                 region: "Yorkshire and the Humber", type: "District" },
  { name: "Harrogate",                 region: "Yorkshire and the Humber", type: "Borough" },
  { name: "Richmondshire",             region: "Yorkshire and the Humber", type: "District" },
  { name: "Ryedale",                   region: "Yorkshire and the Humber", type: "District" },
  { name: "Scarborough",               region: "Yorkshire and the Humber", type: "Borough" },
  { name: "Selby",                     region: "Yorkshire and the Humber", type: "District" },

  // ═══ WALES (22 principal areas) ═══
  { name: "Blaenau Gwent",             region: "Wales", type: "County Borough" },
  { name: "Bridgend",                  region: "Wales", type: "County Borough" },
  { name: "Caerphilly",                region: "Wales", type: "County Borough" },
  { name: "Cardiff",                   region: "Wales", type: "City and County" },
  { name: "Carmarthenshire",           region: "Wales", type: "County" },
  { name: "Ceredigion",                region: "Wales", type: "County" },
  { name: "Conwy",                     region: "Wales", type: "County Borough" },
  { name: "Denbighshire",              region: "Wales", type: "County" },
  { name: "Flintshire",                region: "Wales", type: "County" },
  { name: "Gwynedd",                   region: "Wales", type: "County" },
  { name: "Isle of Anglesey",          region: "Wales", type: "County" },
  { name: "Merthyr Tydfil",            region: "Wales", type: "County Borough" },
  { name: "Monmouthshire",             region: "Wales", type: "County" },
  { name: "Neath Port Talbot",         region: "Wales", type: "County Borough" },
  { name: "Newport",                   region: "Wales", type: "City" },
  { name: "Pembrokeshire",             region: "Wales", type: "County" },
  { name: "Powys",                     region: "Wales", type: "County" },
  { name: "Rhondda Cynon Taf",         region: "Wales", type: "County Borough" },
  { name: "Swansea",                   region: "Wales", type: "City and County" },
  { name: "Torfaen",                   region: "Wales", type: "County Borough" },
  { name: "Vale of Glamorgan",         region: "Wales", type: "County Borough" },
  { name: "Wrexham",                   region: "Wales", type: "County Borough" },

  // ═══ SCOTLAND (32 council areas) ═══
  { name: "Aberdeen City",             region: "Scotland", type: "Council Area" },
  { name: "Aberdeenshire",             region: "Scotland", type: "Council Area" },
  { name: "Angus",                     region: "Scotland", type: "Council Area" },
  { name: "Argyll and Bute",           region: "Scotland", type: "Council Area" },
  { name: "Clackmannanshire",          region: "Scotland", type: "Council Area" },
  { name: "Dumfries and Galloway",     region: "Scotland", type: "Council Area" },
  { name: "Dundee City",               region: "Scotland", type: "Council Area" },
  { name: "East Ayrshire",             region: "Scotland", type: "Council Area" },
  { name: "East Dunbartonshire",       region: "Scotland", type: "Council Area" },
  { name: "East Lothian",              region: "Scotland", type: "Council Area" },
  { name: "East Renfrewshire",         region: "Scotland", type: "Council Area" },
  { name: "Edinburgh (City of)",       region: "Scotland", type: "Council Area" },
  { name: "Falkirk",                   region: "Scotland", type: "Council Area" },
  { name: "Fife",                      region: "Scotland", type: "Council Area" },
  { name: "Glasgow City",              region: "Scotland", type: "Council Area" },
  { name: "Highland",                  region: "Scotland", type: "Council Area" },
  { name: "Inverclyde",                region: "Scotland", type: "Council Area" },
  { name: "Midlothian",                region: "Scotland", type: "Council Area" },
  { name: "Moray",                     region: "Scotland", type: "Council Area" },
  { name: "Na h-Eileanan Siar (Western Isles)", region: "Scotland", type: "Council Area" },
  { name: "North Ayrshire",            region: "Scotland", type: "Council Area" },
  { name: "North Lanarkshire",         region: "Scotland", type: "Council Area" },
  { name: "Orkney Islands",            region: "Scotland", type: "Council Area" },
  { name: "Perth and Kinross",         region: "Scotland", type: "Council Area" },
  { name: "Renfrewshire",              region: "Scotland", type: "Council Area" },
  { name: "Scottish Borders",          region: "Scotland", type: "Council Area" },
  { name: "Shetland Islands",          region: "Scotland", type: "Council Area" },
  { name: "South Ayrshire",            region: "Scotland", type: "Council Area" },
  { name: "South Lanarkshire",         region: "Scotland", type: "Council Area" },
  { name: "Stirling",                  region: "Scotland", type: "Council Area" },
  { name: "West Dunbartonshire",       region: "Scotland", type: "Council Area" },
  { name: "West Lothian",              region: "Scotland", type: "Council Area" },

  // ═══ NORTHERN IRELAND (11 councils) ═══
  { name: "Antrim and Newtownabbey",   region: "Northern Ireland", type: "Borough" },
  { name: "Ards and North Down",       region: "Northern Ireland", type: "Borough" },
  { name: "Armagh City, Banbridge and Craigavon", region: "Northern Ireland", type: "Borough" },
  { name: "Belfast",                   region: "Northern Ireland", type: "City" },
  { name: "Causeway Coast and Glens",  region: "Northern Ireland", type: "Borough" },
  { name: "Derry City and Strabane",   region: "Northern Ireland", type: "City" },
  { name: "Fermanagh and Omagh",       region: "Northern Ireland", type: "District" },
  { name: "Lisburn and Castlereagh",   region: "Northern Ireland", type: "City" },
  { name: "Mid and East Antrim",       region: "Northern Ireland", type: "Borough" },
  { name: "Mid Ulster",                region: "Northern Ireland", type: "District" },
  { name: "Newry, Mourne and Down",    region: "Northern Ireland", type: "District" },
];

// Generate Google search URLs for each council's careers
// Format: "https://www.google.com/search?q=<Council name>+jobs+careers"
const councils = raw.map(c => ({
  ...c,
  url: `https://www.google.com/search?q=${encodeURIComponent(c.name + " council jobs careers")}`,
}));

// Also expose regions for filter chips
export const COUNCIL_REGIONS = [
  "All",
  "London",
  "South East",
  "South West",
  "East of England",
  "East Midlands",
  "West Midlands",
  "North West",
  "North East",
  "Yorkshire and the Humber",
  "Wales",
  "Scotland",
  "Northern Ireland",
];

export default councils;
